#!/bin/bash
# Script to analyze Jenkins build issues

echo "=========================================="
echo "JENKINS BUILD ANALYSIS"
echo "=========================================="
echo ""

echo "🔍 This will help diagnose the Jenkins build issue."
echo ""
echo "Please run this in Jenkins and share the output:"
echo ""
echo "1. Add 'System Check' stage to Jenkinsfile ✅"
echo "2. Run the pipeline"
echo "3. Look at the 'System Check' output"
echo "4. Check the Maven verbose log"
echo ""
echo "=========================================="
echo "WHAT TO LOOK FOR:"
echo "=========================================="
echo ""
echo "🔴 LOW MEMORY (Most Common Issue):"
echo "   Symptom: Build stuck, no progress"
echo "   Check: 'Memory total' < 1GB"
echo "   Fix: Reduce MAVEN_OPTS or get bigger agent"
echo ""
echo "🔴 SLOW DOWNLOAD:"
echo "   Symptom: Stuck at 'Downloading from Maven Central'"
echo "   Check: Maven verbose log shows same file for >5 min"
echo "   Fix: Check network, use Maven mirror"
echo ""
echo "🔴 CPU STARVATION:"
echo "   Symptom: Load average > number of CPUs"
echo "   Check: 'Load average' > nproc"
echo "   Fix: Reduce parallel builds, get more CPU"
echo ""
echo "🔴 DISK FULL:"
echo "   Symptom: 'No space left on device'"
echo "   Check: 'Use%' near 100%"
echo "   Fix: Clean up Jenkins workspace"
echo ""
echo "=========================================="
echo "QUICK FIXES TO TRY:"
echo "=========================================="
echo ""
echo "1. SKIP TESTS TEMPORARILY:"
echo "   Change 'mvn clean package' to 'mvn clean package -DskipTests'"
echo ""
echo "2. USE OFFLINE MODE:"
echo "   Add '-o' to Maven command (uses cached deps only)"
echo ""
echo "3. INCREASE TIMEOUT:"
echo "   Change 'timeout(time: 10)' to 'timeout(time: 30)'"
echo ""
echo "4. BUILD LOCALLY:"
echo "   Build on your machine, push Docker image manually"
echo ""
echo "=========================================="
